package model;
// Generated Nov 8, 2017 10:51:57 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Artikal generated by hbm2java
 */
@Entity
@Table(name="artikal"
    ,catalog="muzicka_prodavnica"
)
public class Artikal  implements java.io.Serializable {


     private Integer idArtikal;
     private String naziv;
     private String tip;
     private String opis;
     private String slika;
     private String redovnaCijena;
     private String popustCijena;
     private int brKomada;

    public Artikal() {
    }

    public Artikal(String naziv, String tip, String opis, String slika, String redovnaCijena, String popustCijena, int brKomada) {
       this.naziv = naziv;
       this.tip = tip;
       this.opis = opis;
       this.slika = slika;
       this.redovnaCijena = redovnaCijena;
       this.popustCijena = popustCijena;
       this.brKomada = brKomada;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_artikal", unique=true, nullable=false)
    public Integer getIdArtikal() {
        return this.idArtikal;
    }
    
    public void setIdArtikal(Integer idArtikal) {
        this.idArtikal = idArtikal;
    }

    
    @Column(name="naziv", nullable=false, length=45)
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }

    
    @Column(name="tip", nullable=false, length=10)
    public String getTip() {
        return this.tip;
    }
    
    public void setTip(String tip) {
        this.tip = tip;
    }

    
    @Column(name="opis", nullable=false, length=200)
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }

    
    @Column(name="slika", nullable=false, length=45)
    public String getSlika() {
        return this.slika;
    }
    
    public void setSlika(String slika) {
        this.slika = slika;
    }

    
    @Column(name="redovna_cijena", nullable=false, length=45)
    public String getRedovnaCijena() {
        return this.redovnaCijena;
    }
    
    public void setRedovnaCijena(String redovnaCijena) {
        this.redovnaCijena = redovnaCijena;
    }

    
    @Column(name="popust_cijena", nullable=false, length=45)
    public String getPopustCijena() {
        return this.popustCijena;
    }
    
    public void setPopustCijena(String popustCijena) {
        this.popustCijena = popustCijena;
    }

    
    @Column(name="br_komada", nullable=false)
    public int getBrKomada() {
        return this.brKomada;
    }
    
    public void setBrKomada(int brKomada) {
        this.brKomada = brKomada;
    }




}


